name: Deploy Next.js App

on:
  push:
    branches:
      - main # Change if deploying a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check Node.js version
        run: node -v

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        env:
          HOST: 159.89.245.206
          USERNAME: root
          TARGET_DIR: /var/www/my-portfolio-site
          APP_NAME: my-portfolio-site
          PORT: 3000

        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            set -e
            echo "Navigating to project directory..."
            cd $TARGET_DIR

            echo "Fetching and resetting to latest GitHub commit..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Building Next.js app..."
            npm run build

            echo "Checking if PM2 is installed..."
            if ! command -v pm2 &> /dev/null
            then
              echo "PM2 not found, installing..."
              npm install -g pm2
            else
              echo "PM2 is already installed"
            fi

            echo "Checking if PM2 process exists..."
            if pm2 list | grep -q $APP_NAME; then
              echo "Restarting application: $APP_NAME"
              pm2 restart $APP_NAME
            else
              echo "Starting application: $APP_NAME"
              pm2 start npm --name $APP_NAME -- start -- --port=$PORT
            fi

            echo "Saving PM2 state..."
            pm2 save
          EOF
